"""Added two new columns: morming_workout and added_sugar

Revision ID: 081ac3f13267
Revises: 814afcb70c67
Create Date: 2026-06-18 22:14:54.151345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '081ac3f13267'
down_revision: Union[str, Sequence[str], None] = '814afcb70c67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailynote', sa.Column('morning_workout', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('dailynote', sa.Column('added_sugar', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dailynote', 'added_sugar')
    op.drop_column('dailynote', 'morning_workout')
    # ### end Alembic commands ###
