"""Transferring book format and language to the reading session log, processing audiobook listening duration

Revision ID: 0e5a29320717
Revises: 36d18b715154
Create Date: 2026-06-12 08:45:08.415022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0e5a29320717'
down_revision: Union[str, Sequence[str], None] = '36d18b715154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'language')
    op.drop_column('book', 'format')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('format', sa.VARCHAR(), nullable=False))
    op.add_column('book', sa.Column('language', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
