"""add read_log column, deleted started and finished columns

Revision ID: 36d18b715154
Revises: c1fc019da257
Create Date: 2026-06-11 22:41:15.857317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '36d18b715154'
down_revision: Union[str, Sequence[str], None] = 'c1fc019da257'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('read_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('book', 'started')
    op.drop_column('book', 'finished')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('finished', sa.VARCHAR(), nullable=True))
    op.add_column('book', sa.Column('started', sa.VARCHAR(), nullable=True))
    op.drop_column('book', 'read_log')
    # ### end Alembic commands ###
