"""Initial migration

Revision ID: 36f56a5ec369
Revises: 
Create Date: 2026-06-17 09:50:24.970029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '36f56a5ec369'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_orig', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genres', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('good_reads', sa.Integer(), nullable=True),
    sa.Column('read_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating_characters', sa.Float(), nullable=False),
    sa.Column('rating_plot', sa.Float(), nullable=False),
    sa.Column('rating_size', sa.Float(), nullable=False),
    sa.Column('rating_prose', sa.Float(), nullable=False),
    sa.Column('rating_ending', sa.Float(), nullable=False),
    sa.Column('rating_depth', sa.Float(), nullable=False),
    sa.Column('rating_atmosphere', sa.Float(), nullable=False),
    sa.Column('rating_rereadability', sa.Float(), nullable=False),
    sa.Column('rating_expected_real', sa.Float(), nullable=False),
    sa.Column('rating_recommend', sa.Float(), nullable=False),
    sa.Column('total_rating', sa.Float(), nullable=False),
    sa.Column('bg_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_modified', sa.Float(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_file_path'), 'book', ['file_path'], unique=True)
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_orig', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genres', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('purchase_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('digital_dist', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('developer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hours_played', sa.Float(), nullable=False),
    sa.Column('hours_to_beat', sa.Float(), nullable=True),
    sa.Column('percent_achievements', sa.Integer(), nullable=False),
    sa.Column('play_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating_optimization', sa.Float(), nullable=False),
    sa.Column('rating_graphics', sa.Float(), nullable=False),
    sa.Column('rating_audio', sa.Float(), nullable=False),
    sa.Column('rating_gameplay', sa.Float(), nullable=False),
    sa.Column('rating_price_quality', sa.Float(), nullable=False),
    sa.Column('rating_story_lore', sa.Float(), nullable=False),
    sa.Column('rating_immersion', sa.Float(), nullable=False),
    sa.Column('rating_replayability', sa.Float(), nullable=False),
    sa.Column('rating_expected_real', sa.Float(), nullable=False),
    sa.Column('rating_cult_status', sa.Float(), nullable=False),
    sa.Column('total_rating', sa.Float(), nullable=False),
    sa.Column('bg_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metacritic', sa.Float(), nullable=True),
    sa.Column('steam', sa.Float(), nullable=True),
    sa.Column('igdb', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_modified', sa.Float(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_file_path'), 'game', ['file_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_file_path'), table_name='game')
    op.drop_table('game')
    op.drop_index(op.f('ix_book_file_path'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
