"""add good_reads column

Revision ID: 6801ce072107
Revises: 97c3ee67abbc
Create Date: 2026-06-10 15:27:26.100449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6801ce072107'
down_revision: Union[str, Sequence[str], None] = '97c3ee67abbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('good_reads', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'good_reads')
    # ### end Alembic commands ###
