"""Add table from module Games

Revision ID: 69e92a9890c6
Revises: 784394f43fcb
Create Date: 2026-06-16 17:08:40.249201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '69e92a9890c6'
down_revision: Union[str, Sequence[str], None] = '784394f43fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_orig', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genres', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('digital_dist', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('developer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('publisher', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hours_played', sa.Float(), nullable=False),
    sa.Column('hours_to_beat', sa.Float(), nullable=True),
    sa.Column('percent_achievements', sa.Integer(), nullable=False),
    sa.Column('play_log', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating_optimization', sa.Float(), nullable=False),
    sa.Column('rating_graphics', sa.Float(), nullable=False),
    sa.Column('rating_audio', sa.Float(), nullable=False),
    sa.Column('rating_gameplay', sa.Float(), nullable=False),
    sa.Column('rating_price_quality', sa.Float(), nullable=False),
    sa.Column('rating_story_lore', sa.Float(), nullable=False),
    sa.Column('rating_immersion', sa.Float(), nullable=False),
    sa.Column('rating_replayability', sa.Float(), nullable=False),
    sa.Column('rating_expected_real', sa.Float(), nullable=False),
    sa.Column('rating_cult_status', sa.Float(), nullable=False),
    sa.Column('total_rating', sa.Float(), nullable=False),
    sa.Column('bg_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metacritic', sa.Float(), nullable=True),
    sa.Column('steam', sa.Float(), nullable=True),
    sa.Column('igdb', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cover', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_modified', sa.Float(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_file_path'), 'game', ['file_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_file_path'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
