"""Publisher Country Addition

Revision ID: 7d0fe4fe91e9
Revises: c7f021a469d4
Create Date: 2026-06-23 14:29:04.506247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '7d0fe4fe91e9'
down_revision: Union[str, Sequence[str], None] = 'c7f021a469d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_dev', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.add_column(sa.Column('country_pub', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('country_pub')
        batch_op.drop_column('country_dev')

    # ### end Alembic commands ###
