"""Added two new tables from daily notes: TimeLog and DailyNote

Revision ID: 814afcb70c67
Revises: 36f56a5ec369
Create Date: 2026-06-17 16:23:31.439629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '814afcb70c67'
down_revision: Union[str, Sequence[str], None] = '36f56a5ec369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dailynote',
    sa.Column('date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sleep_from', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sleep_to', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nap_mins', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('fat_pct', sa.Float(), nullable=True),
    sa.Column('muscle_pct', sa.Float(), nullable=True),
    sa.Column('visceral_fat', sa.Float(), nullable=True),
    sa.Column('illness_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_modified', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_index(op.f('ix_dailynote_file_path'), 'dailynote', ['file_path'], unique=True)
    op.create_table('timelog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('raw_duration', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('daily_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['daily_id'], ['dailynote.date'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timelog')
    op.drop_index(op.f('ix_dailynote_file_path'), table_name='dailynote')
    op.drop_table('dailynote')
    # ### end Alembic commands ###
