"""Added new columns in table DailyNotes: has_content

Revision ID: 8d086f93ca60
Revises: 081ac3f13267
Create Date: 2026-06-19 08:33:18.756738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '8d086f93ca60'
down_revision: Union[str, Sequence[str], None] = '081ac3f13267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailynote', sa.Column('has_content', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dailynote', 'has_content')
    # ### end Alembic commands ###
