"""initial_migration

Revision ID: 97c3ee67abbc
Revises: 
Create Date: 2026-06-09 16:34:53.456802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '97c3ee67abbc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_orig', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country_author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('isbn', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('genres', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('format', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finished', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating_characters', sa.Float(), nullable=False),
    sa.Column('rating_plot', sa.Float(), nullable=False),
    sa.Column('rating_size', sa.Float(), nullable=False),
    sa.Column('rating_prose', sa.Float(), nullable=False),
    sa.Column('rating_ending', sa.Float(), nullable=False),
    sa.Column('rating_depth', sa.Float(), nullable=False),
    sa.Column('rating_atmosphere', sa.Float(), nullable=False),
    sa.Column('rating_rereadability', sa.Float(), nullable=False),
    sa.Column('rating_expected_real', sa.Float(), nullable=False),
    sa.Column('rating_recommend', sa.Float(), nullable=False),
    sa.Column('total_rating', sa.Float(), nullable=False),
    sa.Column('bg_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_modified', sa.Float(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_file_path'), 'book', ['file_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_file_path'), table_name='book')
    op.drop_table('book')
    # ### end Alembic commands ###
