"""Percent ach will be None

Revision ID: abfe2f8b0fe9
Revises: 3b0f716d547e
Create Date: 2026-06-24 09:23:29.227009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'abfe2f8b0fe9'
down_revision: Union[str, Sequence[str], None] = '3b0f716d547e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('percent_achievements',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('percent_achievements',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
