"""Small changes in table timelog

Revision ID: c7f021a469d4
Revises: d3a1a60a54dc
Create Date: 2026-06-22 09:44:20.570080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'c7f021a469d4'
down_revision: Union[str, Sequence[str], None] = 'd3a1a60a54dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timelog', schema=None) as batch_op:
        batch_op.alter_column('category_tag',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_timelog_daily_id'), ['daily_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timelog_daily_id'), table_name='timelog')
    op.alter_column('timelog', 'category_tag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
