"""Added new columns in table DailyNote: steps and calories

Revision ID: d3a1a60a54dc
Revises: 8d086f93ca60
Create Date: 2026-06-19 17:29:23.565486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'd3a1a60a54dc'
down_revision: Union[str, Sequence[str], None] = '8d086f93ca60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dailynote', sa.Column('steps', sa.Integer(), nullable=True))
    op.add_column('dailynote', sa.Column('calories', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dailynote', 'calories')
    op.drop_column('dailynote', 'steps')
    # ### end Alembic commands ###
