"""hourst_to_beat deleted from games

Revision ID: fe26acf13171
Revises: 1bb3f054ea5d
Create Date: 2026-07-21 18:41:41.703609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'fe26acf13171'
down_revision: Union[str, Sequence[str], None] = '1bb3f054ea5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('hours_to_beat')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_to_beat', sa.FLOAT(), nullable=True))

    # ### end Alembic commands ###
